language: julia

sudo: required

os:
  - linux
  - linux
  - windows

julia:
  - 1.0
  - 1
  - nightly

jobs:
  fast_finish: true
  # allow_failures:
  # - julia: nightly

notifications:
  email: false

codecov: true
